MLI/forms/dataset.py
from flask_wtf import FlaskForm
from wtforms import SubmitField


class DataSubmitForm(FlaskForm):
    submit = SubmitField()

MLI/views/algorithm.py
from flask import *
from flask_login import current_user
from ..extension import db
from MLI.models import Algorithm, Dataset, Admin
from MLI.forms.preprocessing import PreForm
from MLI.services import select_name, select_algorithm, select_dataset, select_preprocessing


algorithm = Blueprint("algorithm", __name__)
algorithm_type, algorithm_op_str, dataset_op_str, features, x, y_test, y_pre, x_personal, y_personal = [None] * 9
mse, r2, cross, accu, f1 = [None] * 5


@algorithm.route('/algorithm/<int:id>')
def show_lr(id):
    algorithm = Algorithm.query.filter_by(id=id).first()
    admin = Admin.query.filter_by(id=current_user.id).first()
    if admin:
        admin.algorithm_option = algorithm.id
        db.session.commit()
    else:
        flash("There's something wrong!")

    form = PreForm()

    return render_template('algorithm.html', form=form, name=algorithm.algorithm_name)


@algorithm.route('/algorithm/result/')
def cal_result():
    admin = Admin.query.filter_by(id=current_user.id).first()
    if admin:
        global algorithm_type, algorithm_op_str, dataset_op_str, features, x, y_test, y_pre
        global mse, r2, accu, cross, f1, x_personal, y_personal
        dataset_op = admin.dataset_option
        algorithm_op = admin.algorithm_option
        preprocess_op = list()
        if admin.preprocessing_option:
            preprocess_op.append(admin.preprocessing_option)

        algo = Algorithm.query.filter_by(id=algorithm_op).first()
        data = Dataset.query.filter_by(id=dataset_op).first()
        if algo.type == 2 or algo.type == data.type:
            algorithm_type = algo.type
            algorithm_op_str, dataset_op_str, preprocess_op_str = select_name(dataset_op, algorithm_op, preprocess_op)
            algorithm_fun = select_algorithm(algorithm_op_str)
            dataset_fun = select_dataset(dataset_op_str)
            prepro_fun_list = select_preprocessing(preprocess_op_str)

            if algorithm_type:
                features, x, y_test, y_pre, accu, cross, f1, x_personal, y_personal = algorithm_fun(dataset_fun, prepro_fun_list)
            else:
                features, x, y_test, y_pre, mse, r2, cross, x_personal, y_personal = algorithm_fun(dataset_fun, prepro_fun_list)

            return redirect(url_for('algorithm.show_result', pid=0))

        flash("{} is not suitable for {}. Reselect algorithm or dataset.".format(data.dataset_name, algo.algorithm_name), 'danger')

        return redirect(url_for("algorithm.show_lr", id=algorithm_op))


@algorithm.route('/algorithm/result/<int:pid>')
def show_result(pid):
    global algorithm_type, algorithm_op_str, dataset_op_str, features, x, y_test, y_pre
    global mse, r2, accu, cross, f1, x_personal, y_personal
    if algorithm_type:
        return render_template('result_classify.html', features=features, x=x, y_test=y_test, y_pre=y_pre, accu=accu, cross=cross, f1=f1,
                               algorithm_name=algorithm_op_str, dataset_name=dataset_op_str,
                               x_personal=x_personal[pid], y_personal=y_personal[pid], pid=(pid+1) % 10, userid=current_user.id)
    else:
        return render_template('result.html', features=features, x=x, y_test=y_test, y_pre=y_pre, mse=mse, r2=r2, cross=cross,
                               algorithm_name=algorithm_op_str, dataset_name=dataset_op_str,
                               x_personal=x_personal[pid], y_personal=y_personal[pid], pid=(pid+1) % 10, userid=current_user.id)

MLI/views/base.py
from flask import *
from flask_login import login_user, current_user
from ..extension import db
from ..models import Admin

login = Blueprint("login", __name__)


@login.route("/")
def logo():
    if current_user.is_authenticated:
        pass
    else:
        admin = Admin()
        admin.username = 'admin'
        admin.password = '123456'
        db.session.add(admin)
        db.session.commit()
        login_user(admin, remember=True)
    return render_template('base.html')


@login.route("/autologin")
def login_flash():
    flash("You have been automatically logged in~", 'primary')
    flash("Username: admin  Password: 123456", 'primary')

    return redirect(url_for('login.logo'))


@login.route("/hidden")
def hidden():
    flash("Congratulations on finding the hidden function! But nothing happens~", 'info')

    return redirect(url_for('login.logo'))

MLI/views/dataset.py
from flask import *
from flask_login import current_user
from ..extension import db
from MLI.services.dataset import house_data, diabetes_data, wine_data
from MLI.models import Admin, Dataset, Algorithm

dataset = Blueprint('dataset', __name__)


@dataset.route('/dataset')
def show_dataset():
    datasum, tmp_dict = dict(), dict()
    for (i, f) in enumerate([house_data(), diabetes_data(), wine_data()]):
        size, tmp_features, tmp_x, tmp_y = f
        tmp_dict['features'] = tmp_features
        tmp_dict['X'] = tmp_x
        tmp_dict['y'] = tmp_y
        tmp_dict['size'] = size
        datasum[i+1] = tmp_dict.copy()

    return render_template('dataset.html', data=datasum)


@dataset.route('/dataset/<int:id>')
def choose_dataset(id):
    admin = Admin.query.filter_by(id=current_user.id).first()
    if admin:
        algorithm = Algorithm.query.filter_by(id=admin.algorithm_option).first()
        dataset = Dataset.query.filter_by(id=id).first()
        if algorithm.type == 2 or algorithm.type == dataset.type:
            admin.dataset_option = id
            db.session.commit()
            flash("You have chosen {}! Move on~".format(dataset.dataset_name), 'info')
        else:
            flash("{} is not suitable for {}. Reselect.".format(dataset.dataset_name, algorithm.algorithm_name), 'danger')
            return redirect(url_for('dataset.show_dataset'))
    else:
        flash("There's something wrong!", 'danger')
    return redirect(url_for('algorithm.show_lr', id=admin.algorithm_option))

MLI/views/preprocessing.py
from flask import *
from flask_login import current_user
from ..extension import db
from MLI.models import Preprocessing, Admin
from MLI.forms.preprocessing import PreForm

preprocessing = Blueprint("preprocessing", __name__)


@preprocessing.route('/pre', methods=["POST"])
def preprocess():
    form = PreForm()
    id_list = list()  # store chosen preprocess
    if form.Standardization.data:
        pre = Preprocessing.query.filter_by(preprocessing_name='Standardization').first()
        id_list.append(pre.id)
    admin = Admin.query.filter_by(id=current_user.id).first()
    admin.preprocessing_option = None if len(id_list) < 1 else id_list[0]  # commit the first one
    db.session.commit()
    flash("Excellent choice! Move on~", 'info')
    return redirect(url_for('algorithm.show_lr', id=admin.algorithm_option))

MLI/templates/algorithm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>
    <!--<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">-->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<style>
    body {
        position: relative;
    }
    ul li a{
        margin-top: 3px;
        font-size: 25px;
    }
    #section1, #section3, #section5, #section7{
        background-image:url("/static/back.png");
    }
</style>

{% for message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ message[0] }}" style="margin-top:85px">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message[1] }}
    </div>
{% endfor %}

<body data-spy="scroll" data-target=".navbar" data-offset="50">

<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
    <a class="navbar-brand" href="{{ url_for('login.logo') }}" style="color:#FF7F50;font-size:40px;font-weight:bolder">Home</a>
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="#section1">DataSet</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#section2"></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#section3">Preprocessing</a>
        </li>
        <li>
            <a class="nav-link" href="#section4"></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#section5">Model</a>
        </li>
        <li>
            <a class="nav-link" href="#section6"></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#section7">Result</a>
        </li>
    </ul>
</nav>

<div id="section1" class="container-fluid" style="padding-top:120px;padding-bottom:50px">
    <h1 style="margin-left:15px">Step 1. Dataset</h1>
    <p class="text-center font-italic" style="color:#FF7F50;font-size:35px;margin-top:20px">We provide 3 optional datasets!</p>
    <a class="btn btn-success" style="margin-top:15px;margin-left:44vw;font-size:30px;color:#FFF8DC;" href="{{ url_for('dataset.show_dataset') }}">Get Data</a>
</div>

<div id="section2" class="container-fluid bg-warning" style="padding-top:8px;padding-bottom:8px"></div>

<div id="section3" class="container-fluid" style="padding-top:50px;padding-bottom:50px">
    <h1 style="margin-left:15px">Setp 2. Preprocessing</h1>
    <p style="font-size:35px;color:#FF7F50;margin-top:15px" class="text-center font-italic">Choose your preprocessing methods!</p>
    <form class="form" method="post" action="{{ url_for('preprocessing.preprocess') }}">
        <div class="row">
            <div class="form-check col">
                <label class="form-check-label">
                    {{ form.Standardization(class="form-check-input", style="margin-left:20px") }}
                    {{ form.Standardization.label(style="font-size:22px;margin-left:35px") }}
                </label>
            </div>
            <div class="form-check col">
                <label class="form-check-label">
                    {{ form.Nothing(class="form-check-input") }}
                    {{ form.Nothing.label(style="font-size:22px") }}
                </label>
            </div>
            <div class="form-check col">
                <label class="form-check-label">
                    {{ form.Nothing_1(class="form-check-input") }}
                    {{ form.Nothing_1.label(style="font-size:22px") }}
                </label>
            </div>
        </div>
        <div class="row">
            {{ form.submit(class="btn btn-success", style="margin-top:15px;margin-left:45vw;font-size:30px;color:#FFF8DC;") }}
        </div>
    </form>
</div>

<div id="section4" class="container-fluid bg-warning" style="padding-top:8px;padding-bottom:8px"></div>

<div id="section5" class="container-fluid bg-info" style="padding-top:50px;padding-bottom:50px">
    <h1 style="margin-left:10px">Step 3. Model </h1>
    <p style="font-size:35px;color:#FF7F50;margin-top:15px" class="text-center font-italic">You have chosen <span style="font-weight:bolder">{{ name }}</span> Model</p>
    <a class="btn btn-success" style="margin-top:15px;margin-left:39vw;font-size:30px;color:#FFF8DC;" href="#">Change from Home</a>
</div>

<div id="section6" class="container-fluid bg-warning" style="padding-top:8px;padding-bottom:8px"></div>

<div id="section7" class="container-fluid bg-info" style="padding-top:50px;padding-bottom:50px">
    <div class="row">
        <p style="font-size:45px;color:#FF7F50;margin-top:12px;margin-left:36vw"><span style="font-weight:bolder">Now</span></p>
        <a class="btn btn-success" style="margin-bottom: 30px;margin-top:15px;margin-left:18px;font-size:35px;color:#FFF8DC;" href="{{ url_for('algorithm.cal_result') }}">Get Result</a>
        <p style="font-size:45px;color:#FF7F50;margin-top:12px;margin-left:18px"><span style="font-weight:bolder">!</span></p>
    </div>
</div>
</body>
</html>

MLI/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>
    <!--<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">-->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>

<style>
    h1{
        font-family: "Brush Script MT";
        font-weight: bolder;
        font-size: 100px;
    }
    body{
        background-image: url('/static/logo.png');
        background-size: 100%;
    }
    .container{
        margin-top: 38vw;
    }
    [class*="col-"] {
      padding-left: 0;
      padding-right: 0;
    }
    .row {
      margin-left: 0;
      margin-right: 0;
    }
</style>

<body>

{% for message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ message[0] }}">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message[1] }}
    </div>
{% endfor %}

<!-- Navigate -->
<div class="row bg-dark">
    <div class="col-8">
    <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" style="font-size:40px;color:#FF7F50;font-weight: bolder;"> Get Start</button>
    <div class="dropdown-menu">
        <a class="dropdown-item" href="{{ url_for('algorithm.show_lr', id=1) }}" style="font-size:18px">Linear Regression</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{{ url_for('algorithm.show_lr', id=2) }}" style="font-size:18px">Logistic Regression</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item disabled" href="#" style="font-size:18px">Decision Tree</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item disabled" href="#" style="font-size:18px">Random Forest</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item disabled" href="#" style="font-size:18px">SVM</a>
    </div>
    </div>
    <div class="col-2">
        <input class="form-control" type="text" placeholder="Baby!  Just tell me " style="margin-top: 17px;">
    </div>
    <div class="col-1">
        <button class="btn btn-dark" type="submit" style="margin-top: 13px;color:#FF7F50;font-weight: bolder;font-size:21px">Search</button>
    </div>
    <div class="col-1">
        <a class="btn btn-warning" href="{{ url_for('login.hidden') }}" style="margin-top:13px;font-size: 20px;font-weight: bolder;color:#FFF8DC">Click</a>
    </div>
</div>
<div class="container row">
    <a class="btn btn-warning float-right" style="margin-left:42vw;font-size:35px;font-weight:bolder;color:#FFF8DC" href="{{ url_for('login.login_flash') }}">Sign in</a>
</div>
</body>
</html>

MLI/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>
    <!--<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">-->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<style>
  body {
      position: relative;
  }
  ul li a{
      margin-top: 3px;
      font-size: 25px;
  }
  #section1, #section2, #section3, #section4{
      background-image:url("/static/back.png");
  }
  .con{
      width:100%;
  }
  .pic{
      float:right;
      width:50%;
  }
  .text{
      float:left;
      width:50%;
  }
</style>

{% for message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ message[0] }}">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message[1] }}
    </div>
{% endfor %}

<body data-spy="scroll" data-target=".navbar" data-offset="50">

<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
    <a class="navbar-brand" href="{{ url_for('login.logo') }}" style="color:#FF7F50;font-size:40px;font-weight:bolder">Home</a>
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="#section1"></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#section2"></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#section3"></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#section4"></a>
        </li>
    </ul>
</nav>

<div id="section1" class="container-fluid" style="padding-top:110px;padding-bottom:20px;">
    <h1 style="color:#FF7F50;font-weight:bolder" class="text-center font-italic">{{ algorithm_name }}</h1>
    <h2 class="text-center font-italic text-warning">on</h2>
    <h1 style="color:#FF7F50;font-weight:bolder;margin-bottom:20px" class="text-center font-italic">{{ dataset_name }}</h1>
    <h2 style="font-size:30px;font-weight:bold;" class="font-italic">Part of Prediction</h2>
    <table class="table table-striped table-hover">
        <thead class="bg-warning">
        <tr>
            <th> </th>
            {% for feature in features %}
                <th>{{ feature }}</th>
            {% endfor %}
            <th class="text-danger">Label</th>
            <th class="text-info">Predict</th>
        </tr>
        </thead>
        <tbody>
        {% for piece in x %}
            <tr>
                <th>{{ loop.index0 }}</th>
                {% for d in piece %}
                    <th>{{ d }}</th>
                {% endfor %}
                <th class="text-danger">{{ y_test[loop.index0] }}</th>
                <th class="text-info">{{ y_pre[loop.index0] }}</th>
            </tr>
        {% endfor %}
        <tr>
            <th>...</th>
            {% for i in features %}
                <th>...</th>
            {% endfor %}
            <th>...</th>
            <th>...</th>
        </tr>
        </tbody>
    </table>
</div>

<div id="section2" class="container-fluid bg-warning" style="padding-top:20px;padding-bottom:80px">
    <h2 style="font-size:30px;font-weight:bold;" class="font-italic">Target</h2>
    <div class="con">
        <div class="text">
            <p style="font-size:22px;font-weight:bold;margin-top:10px">MSE(Mean Square Error) in Inference: <span style="color:#FF7F50;font-size:22px">{{ mse }}</span></p>
            <p style="font-size:22px;font-weight:bold;">MSE in Cross Validation: <span style="color:#FF7F50;font-size:22px">{{ cross }}</span></p>
            <p>The First one is MSE in test dataset. The second one is MSE in validation dataset.
                MSE is the expectation of the difference between groundtruth and prediction.</p>
            <p style="font-size:22px;font-weight:bold;">R2: <span style="color:#FF7F50;font-size:22px">{{ r2 }}</span></p>
            <p>When R2 shows negative, it proves that model doesn't fit well thus it is completely unusable.</p>
        </div>
        <div class="pic">
            <img src="/static/{{ userid }}.png" height="350px" width="450px" />
        </div>
    </div>
</div>

<div id="section3" class="container-fluid bg-secondary" style="padding-top:280px;padding-bottom:50px;">
    <h2 style="font-size:30px;font-weight:bold;" class="font-italic">Predict for Yourself!</h2>
        <table class="table table-striped table-hover">
        <thead class="bg-warning">
        <tr>
            {% for feature in features %}
                <th>{{ feature }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for d in x_personal %}
                <th>{{ d }}</th>
            {% endfor %}
        </tr>
        </tbody>
    </table>
    <p class="text-center" style="font-weight:bolder;font-size:25px">Predict: <span class="text-info">{{ y_personal }}</span></p>
    <a class="btn btn-success" style="margin-top:20px;margin-left:38vw;font-size:20px;color:#FFF8DC;" href="{{ url_for('algorithm.show_result', pid=pid) }}">Get Another Random Data</a>
</div>

<div id="section4" class="container-fluid bg-secondary" style="padding-top:20px;padding-bottom:20px">

</div>

</body>
</html>

MLI/templates/result_classify.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>
    <!--<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">-->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<style>
  body {
      position: relative;
  }
  ul li a{
      margin-top: 3px;
      font-size: 25px;
  }
  #section1, #section2, #section3, #section4{
      background-image:url("/static/back.png");
  }
  .con{
      width:100%;
  }
  .pic{
      float:right;
      width:50%;
  }
  .text{
      float:left;
      width:50%;
  }
</style>

{% for message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ message[0] }}">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message[1] }}
    </div>
{% endfor %}

<body data-spy="scroll" data-target=".navbar" data-offset="50">

<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
    <a class="navbar-brand" href="{{ url_for('login.logo') }}" style="color:#FF7F50;font-size:40px;font-weight:bolder">Home</a>
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="#section1"></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#section2"></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#section3"></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#section4"></a>
        </li>
    </ul>
</nav>

<div id="section1" class="container-fluid" style="padding-top:110px;padding-bottom:20px;">
    <h1 style="color:#FF7F50;font-weight:bolder" class="text-center font-italic">{{ algorithm_name }}</h1>
    <h2 class="text-center font-italic text-warning">on</h2>
    <h1 style="color:#FF7F50;font-weight:bolder;margin-bottom:20px" class="text-center font-italic">{{ dataset_name }}</h1>
    <h2 style="font-size:30px;font-weight:bold;" class="font-italic">Part of Prediction</h2>
    <table class="table table-striped table-hover">
        <thead class="bg-warning">
        <tr>
            <th> </th>
            {% for feature in features %}
                <th>{{ feature }}</th>
            {% endfor %}
            <th class="text-danger">Label</th>
            <th class="text-info">Predict</th>
        </tr>
        </thead>
        <tbody>
        {% for piece in x %}
            <tr>
                <th>{{ loop.index0 }}</th>
                {% for d in piece %}
                    <th>{{ d }}</th>
                {% endfor %}
                <th class="text-danger">{{ y_test[loop.index0] }}</th>
                <th class="text-info">{{ y_pre[loop.index0] }}</th>
            </tr>
        {% endfor %}
        <tr>
            <th>...</th>
            {% for i in features %}
                <th>...</th>
            {% endfor %}
            <th>...</th>
            <th>...</th>
        </tr>
        </tbody>
    </table>
</div>

<div id="section2" class="container-fluid bg-warning" style="padding-top:20px;padding-bottom:80px">
    <h2 style="font-size:30px;font-weight:bold;" class="font-italic">Target</h2>
    <div class="con">
        <div class="text">
            <p style="font-size:22px;font-weight:bold;margin-top:10px">Accuracy in Inference: <span style="color:#FF7F50;font-size:22px">{{ accu }}</span></p>
            <p style="font-size:22px;font-weight:bold;">Accuracy in Cross Validation: <span style="color:#FF7F50;font-size:22px">{{ cross }}</span></p>
            <p>The First one is accuracy in test dataset. The second one is accuracy in validation dataset.</p>
            <p style="font-size:22px;font-weight:bold;">F1-Score: <span style="color:#FF7F50;font-size:22px">{{ f1 }}</span></p>
            <p>When precision is high, recall tends to be low and vice versa. F1 is harmonic average of precision and recall.</p>
        </div>
        <div class="pic">
            <img src="/MLI/static/{{ userid }}.png" height="350px" width="450px" />
        </div>
    </div>
</div>

<div id="section3" class="container-fluid bg-secondary" style="padding-top:280px;padding-bottom:50px;">
    <h2 style="font-size:30px;font-weight:bold;" class="font-italic">Predict for Yourself!</h2>
        <table class="table table-striped table-hover">
        <thead class="bg-warning">
        <tr>
            {% for feature in features %}
                <th>{{ feature }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for d in x_personal %}
                <th>{{ d }}</th>
            {% endfor %}
        </tr>
        </tbody>
    </table>
    <p class="text-center" style="font-weight:bolder;font-size:25px">Predict: <span class="text-info">{{ y_personal }}</span></p>
    <a class="btn btn-success" style="margin-top:20px;margin-left:38vw;font-size:20px;color:#FFF8DC;" href="{{ url_for('algorithm.show_result', pid=pid) }}">Get Another Random Data</a>
</div>

<div id="section4" class="container-fluid bg-secondary" style="padding-top:20px;padding-bottom:20px">

</div>

</body>
</html>